export default () => ({
  is_playing: false,
  player_volume: 55,
  current_stream: {
    name: "3a_Orelha",
    url: "https://orelha.xyz:8000/radio.mp3",
  },
  station: {
    id: 1,
    name: "3a Orelha",
    shortcode: "station_name",
    description: "Station Description.",
    frontend: "icecast",
    backend: "liquidsoap",
    listen_url: "https://orelha.xyz:8000/radio.mp3",
    url: "3a-Orelha.space",
    playlist_pls_url: "https://orelha.xyz/public/3a_orelha/playlist.pls",
    playlist_m3u_url: "https://orelha.xyz/public/3a_orelha/playlist.m3u",
    is_public: true,
    mounts: [],
    remotes: [],
  },
  listeners: {
    current: 0,
    unique: 0,
    total: 0,
  },
  live: {
    is_live: false,
    streamer_name: "",
    broadcast_start: null,
  },
  now_playing: {
    elapsed: 0,
    remaining: 0,
    sh_id: 0,
    played_at: 0,
    duration: 0,
    playlist: "default",
    streamer: "",
    is_request: false,
    song: {
      id: "",
      text: "",
      artist: "",
      title: "",
      album: "",
      genre: "",
      lyrics: "",
      art: "",
      custom_fields: {},
    },
  },
  playing_next: {
    cued_at: 0,
    duration: 0,
    playlist: "default",
    is_request: false,
    song: {
      id: "",
      text: "",
      artist: "",
      title: "",
      album: "",
      genre: "",
      lyrics: "",
      art: "",
      custom_fields: {},
    },
  },
  song_history: [],
})
